"""Typed local runtime roles."""

from miniverl.runtime.generation import (
    BackendCapabilities,
    BackendLifecycleState,
    BackendMetrics,
    GenerationBackend,
    GenerationBatch,
    GenerationRequest,
    GenerationResult,
    PolicySnapshot,
    PolicySyncResult,
    ReproducibilityClass,
    RolloutBackendKind,
    RolloutGroupIdentity,
    RolloutPolicyIdentity,
    SamplingParameters,
    derive_sample_seed,
)
from miniverl.runtime.roles import (
    ActorPolicy,
    ArtifactBridge,
    EvaluationRuntime,
    LocalArtifactBridge,
    LocalRoleGraph,
    ReferencePolicy,
    RewardOrVerifier,
    RolloutRuntime,
    TargetBuilder,
    TeacherPolicy,
    UpdateRuntime,
)

__all__ = [
    "ActorPolicy",
    "RolloutRuntime",
    "TeacherPolicy",
    "ReferencePolicy",
    "RewardOrVerifier",
    "TargetBuilder",
    "UpdateRuntime",
    "EvaluationRuntime",
    "ArtifactBridge",
    "LocalArtifactBridge",
    "LocalRoleGraph",
    "BackendCapabilities",
    "BackendLifecycleState",
    "BackendMetrics",
    "GenerationBackend",
    "GenerationBatch",
    "GenerationRequest",
    "GenerationResult",
    "PolicySnapshot",
    "PolicySyncResult",
    "ReproducibilityClass",
    "RolloutBackendKind",
    "RolloutGroupIdentity",
    "RolloutPolicyIdentity",
    "SamplingParameters",
    "derive_sample_seed",
]
