"""Reversible text-span <-> token-span transcript codec.

Design rule: **segment-wise tokenization**.  Every transcript segment is
tokenized on its own and the ids are concatenated.  Two consequences matter:

1. A token can never straddle a provenance boundary, so "this token was
   generated by the model" is exact rather than approximate.
2. The teacher's render of the shared segments produces *byte-identical token
   ids*, which is what makes privileged-context alignment checkable.

The cost is that concatenated segment ids may differ from tokenizing the whole
string in one call (no BPE merges across a boundary).  That is a deliberate
trade: provenance exactness beats a handful of saved tokens, and the model is
trained on exactly the sequence it is later served.

Context segments carry the trailing ``<|im_start|>assistant\\n`` header of the
turn they precede.  Generation therefore begins exactly at the first token of a
model span, and no forced scaffolding token is ever marked model-generated.
"""

from __future__ import annotations

from collections.abc import Sequence
from dataclasses import dataclass, field
from typing import Protocol

from miniverl.errors import TrajectoryError
from miniverl.schemas.trajectory import (
    Span,
    SpanType,
    TerminationReason,
    Trajectory,
    Turn,
    VerificationRecord,
)
from miniverl.trajectory.alignment import SEGMENT_KEY
from miniverl.trajectory.masks import build_masks

__all__ = ["ChatFormat", "Segment", "TranscriptBuilder", "TokenizerLike", "token_index_at_char"]


class TokenizerLike(Protocol):
    """The tiny slice of tokenizer behaviour miniVERL depends on.

    The four scalars are declared read-only so an implementation may expose them
    either as plain attributes or as properties.
    """

    @property
    def vocab_size(self) -> int:
        """Size of the output vocabulary."""
        ...

    @property
    def eos_token_id(self) -> int:
        """Token id that ends a sequence."""
        ...

    @property
    def pad_token_id(self) -> int:
        """Token id used for padding."""
        ...

    @property
    def fingerprint(self) -> str:
        """Behavioural hash: equal iff two tokenizers tokenize identically."""
        ...

    def encode(self, text: str) -> list[int]:
        """Tokenize without adding any implicit special tokens."""
        ...

    def decode(self, token_ids: Sequence[int]) -> str:
        """Detokenize without skipping special tokens."""
        ...


@dataclass(frozen=True)
class ChatFormat:
    """ChatML-style turn framing.

    Both the toy tokenizer and the Qwen tokenizers know ``<|im_start|>`` and
    ``<|im_end|>`` as single tokens, so no vocabulary resize is ever required.
    """

    turn_start: str = "<|im_start|>"
    turn_end: str = "<|im_end|>"
    newline: str = "\n"

    def header(self, role: str) -> str:
        """Opening scaffolding for ``role``."""
        return f"{self.turn_start}{role}{self.newline}"

    def close(self) -> str:
        """Closing scaffolding for a turn."""
        return f"{self.turn_end}{self.newline}"


@dataclass
class Segment:
    """One contiguous piece of transcript with a single provenance type."""

    key: str
    span_type: SpanType
    turn_id: int
    text: str = ""
    token_ids: list[int] = field(default_factory=list)
    tool_name: str | None = None
    tool_call_id: str | None = None
    env_state_id: str | None = None
    metadata: dict[str, object] = field(default_factory=dict)

    @property
    def is_pretokenized(self) -> bool:
        """``True`` when the segment carries model-sampled ids verbatim."""
        return bool(self.token_ids)


def token_index_at_char(tokenizer: TokenizerLike, token_ids: Sequence[int], char_index: int) -> int:
    """Token index whose decoded prefix first reaches ``char_index`` characters.

    Used to split a *sampled* token sequence at a text landmark without ever
    re-tokenizing it.  When a token straddles the landmark the split is placed
    **before** that token, so the straddling token joins the later (typed) span
    rather than the untyped prefix.
    """
    if char_index <= 0:
        return 0
    for i in range(1, len(token_ids) + 1):
        prefix_len = len(tokenizer.decode(token_ids[:i]))
        if prefix_len == char_index:
            return i
        if prefix_len > char_index:
            return i - 1
    return len(token_ids)


class TranscriptBuilder:
    """Accumulates segments and freezes them into a :class:`Trajectory`."""

    def __init__(self, tokenizer: TokenizerLike, chat_format: ChatFormat | None = None) -> None:
        self.tokenizer = tokenizer
        self.chat_format = chat_format or ChatFormat()
        self._segments: list[Segment] = []
        self._token_ids: list[int] = []
        self._keys: set[str] = set()

    # -- construction ---------------------------------------------------

    def add(self, segment: Segment) -> Segment:
        """Append a segment, tokenizing it when ids were not supplied."""
        if segment.key in self._keys:
            raise TrajectoryError(f"duplicate transcript segment key {segment.key!r}")
        if not segment.is_pretokenized:
            if not segment.text:
                raise TrajectoryError(f"segment {segment.key!r} is empty")
            segment.token_ids = list(self.tokenizer.encode(segment.text))
        if not segment.token_ids:
            raise TrajectoryError(
                f"segment {segment.key!r} tokenized to zero tokens (text={segment.text!r})"
            )
        if not segment.text:
            segment.text = self.tokenizer.decode(segment.token_ids)
        self._keys.add(segment.key)
        self._segments.append(segment)
        self._token_ids.extend(segment.token_ids)
        return segment

    def add_context(
        self,
        *,
        key: str,
        span_type: SpanType,
        turn_id: int,
        role: str,
        body: str,
        close_previous: bool = False,
        open_next_assistant: bool = True,
        tool_call_id: str | None = None,
        env_state_id: str | None = None,
    ) -> Segment:
        """Add a fully framed context turn (system / user / tool result)."""
        fmt = self.chat_format
        text = ""
        if close_previous:
            text += fmt.close()
        text += fmt.header(role) + body + fmt.close()
        if open_next_assistant:
            text += fmt.header("assistant")
        return self.add(
            Segment(
                key=key,
                span_type=span_type,
                turn_id=turn_id,
                text=text,
                tool_call_id=tool_call_id,
                env_state_id=env_state_id,
            )
        )

    # -- inspection -----------------------------------------------------

    @property
    def token_ids(self) -> list[int]:
        """Current token sequence."""
        return list(self._token_ids)

    @property
    def length(self) -> int:
        """Current token count."""
        return len(self._token_ids)

    @property
    def segments(self) -> list[Segment]:
        """Segments added so far, in order."""
        return list(self._segments)

    def text(self) -> str:
        """Concatenated segment text (exactly what the model saw)."""
        return "".join(s.text for s in self._segments)

    # -- freezing -------------------------------------------------------

    def spans(self) -> list[Span]:
        """Materialize the span partition."""
        spans: list[Span] = []
        cursor = 0
        for segment in self._segments:
            end = cursor + len(segment.token_ids)
            metadata = dict(segment.metadata)
            metadata[SEGMENT_KEY] = segment.key
            spans.append(
                Span(
                    span_type=segment.span_type,
                    start=cursor,
                    end=end,
                    turn_id=segment.turn_id,
                    text=segment.text,
                    tool_name=segment.tool_name,
                    tool_call_id=segment.tool_call_id,
                    env_state_id=segment.env_state_id,
                    metadata=metadata,
                )
            )
            cursor = end
        return spans

    def build(
        self,
        *,
        trajectory_id: str,
        task_id: str,
        environment: str,
        model_id: str,
        model_revision: str | None,
        policy_version: int,
        termination_reason: TerminationReason,
        turns: Sequence[Turn] = (),
        verification: VerificationRecord | None = None,
        generated_token_count: int = 0,
        invalid_tool_calls: int = 0,
        metadata: dict[str, object] | None = None,
    ) -> Trajectory:
        """Freeze the accumulated segments into a validated trajectory."""
        if not self._segments:
            raise TrajectoryError("cannot build a trajectory with no segments")
        spans = self.spans()
        token_ids = list(self._token_ids)
        model_mask, critical_mask = build_masks(spans, len(token_ids))
        return Trajectory(
            trajectory_id=trajectory_id,
            task_id=task_id,
            environment=environment,
            token_ids=token_ids,
            attention_mask=[1] * len(token_ids),
            model_generated_mask=model_mask,
            critical_mask=critical_mask,
            spans=spans,
            turns=list(turns),
            policy_version=policy_version,
            tokenizer_fingerprint=self.tokenizer.fingerprint,
            model_id=model_id,
            model_revision=model_revision,
            verification=verification,
            termination_reason=termination_reason,
            generated_token_count=generated_token_count,
            invalid_tool_calls=invalid_tool_calls,
            metadata=dict(metadata or {}),
        )
