actor_rollout_ref:
  actor:
    entropy_coeff: 0
    fsdp_config:
      optimizer_offload: false
      param_offload: false
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    optim:
      lr: 1.0e-06
    ppo_max_token_len_per_gpu: 3000
    ppo_micro_batch_size_per_gpu: 2
    ppo_mini_batch_size: 256
    use_dynamic_bsz: true
    use_kl_loss: true
  model:
    enable_gradient_checkpointing: true
    path: Qwen/Qwen3-4B
    use_remove_padding: true
  ref:
    fsdp_config:
      param_offload: true
    log_prob_max_token_len_per_gpu: 8192
    log_prob_micro_batch_size_per_gpu: 2
    log_prob_use_dynamic_bsz: true
  rollout:
    checkpoint_engine:
      update_weights_bucket_megabytes: 4096
    enable_chunked_prefill: false
    enforce_eager: false
    free_cache_engine: true
    gpu_memory_utilization: 0.6
    log_prob_max_token_len_per_gpu: 4096
    log_prob_micro_batch_size_per_gpu: 2
    log_prob_use_dynamic_bsz: true
    n: 5
    name: vllm
    tensor_model_parallel_size: 2
algorithm:
  adv_estimator: grpo
  use_kl_in_reward: false
data:
  filter_overlong_prompts: true
  max_prompt_length: 1024
  max_response_length: 1024
  train_batch_size: 512
  train_files: /upstream-home/data/gsm8k/train.parquet
  truncation: error
  val_files: /upstream-home/data/gsm8k/test.parquet
trainer:
  critic_warmup: 0
  experiment_name: glm41v_9b_function_rm
  logger:
  - console
  - wandb
  n_gpus_per_node: 8
  nnodes: 1
  project_name: verl_grpo_example_geo3k
  save_freq: 20
  test_freq: 5
  total_epochs: 15
